name: CI/CD

on:
  push:
    branches: [main, master]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main, master]
    paths-ignore:
      - README.md

jobs:
  build:
    name: Build
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: |
          Set-Location Source
          nuget restore

      - name: Build assemblies
        run: msbuild Source\ValheimDiscord.sln /p:Configuration=Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ValheimDiscord
          path: |
            ValheimDiscord/bin/Release/Discord.*.dll
            ValheimDiscord/bin/Release/Microsoft.*.dll
            ValheimDiscord/bin/Release/Newtonsoft.Json.dll
            ValheimDiscord/bin/Release/System.*.dll
            ValheimDiscord/bin/Release/ValheimDiscord.dll